### ISSUE TITLE
Import error on Google Colab

### ISSUE THREAD

**Issue by kunifujiwara** [koito19960406/ZenSVI#77]
I got this error when running "from zensvi.cv import Segmenter" on Google Colab.

----------------
0.12.7
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in _get_module(self, module_name)
   1602         try:
-> 1603             return importlib.import_module("." + module_name, self.__name__)
   1604         except Exception as e:

20 frames
/usr/lib/python3.10/importlib/__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

/usr/lib/python3.10/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.10/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.10/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/image_processing_auto.py in <module>
     26 from ...dynamic_module_utils import get_class_from_dynamic_module, resolve_trust_remote_code
---> 27 from ...image_processing_utils import BaseImageProcessor, ImageProcessingMixin
     28 from ...image_processing_utils_fast import BaseImageProcessorFast

/usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils.py in <module>
     20 from .image_processing_base import BatchFeature, ImageProcessingMixin
---> 21 from .image_transforms import center_crop, normalize, rescale
     22 from .image_utils import ChannelDimension

/usr/local/lib/python3.10/dist-packages/transformers/image_transforms.py in <module>
     21 
---> 22 from .image_utils import (
     23     ChannelDimension,

/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py in <module>
     57     if is_torchvision_available():
---> 58         from torchvision.transforms import InterpolationMode
     59 

/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py in <module>
      9 from .extension import _HAS_OPS  # usort:skip
---> 10 from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
     11 

/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py in <module>
    162 
--> 163 @torch.library.register_fake("torchvision::nms")
    164 def meta_nms(dets, scores, iou_threshold):

AttributeError: module 'torch.library' has no attribute 'register_fake'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-4-b7bec7cc9e4c> in <cell line: 6>()
      4 
      5 from zensvi.download import GSVDownloader, MLYDownloader
----> 6 from zensvi.cv import Segmenter
      7 from zensvi.transform import ImageTransformer
      8 import geojson

/usr/local/lib/python3.10/dist-packages/zensvi/cv/__init__.py in <module>
----> 1 from .segmentation import *
      2 from .low_level import *
      3 from .classification import *
      4 from .depth_estimation import *

/usr/local/lib/python3.10/dist-packages/zensvi/cv/segmentation/__init__.py in <module>
----> 1 from .segmentation import *

/usr/local/lib/python3.10/dist-packages/zensvi/cv/segmentation/segmentation.py in <module>
      9 from concurrent.futures import ThreadPoolExecutor, as_completed
     10 from collections import namedtuple
---> 11 from transformers import AutoImageProcessor, Mask2FormerForUniversalSegmentation
     12 from tqdm.auto import tqdm
     13 import json

/usr/lib/python3.10/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in __getattr__(self, name)
   1592         elif name in self._class_to_module.keys():
   1593             module = self._get_module(self._class_to_module[name])
-> 1594             value = getattr(module, name)
   1595         else:
   1596             raise AttributeError(f"module {self.__name__} has no attribute {name}")

/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in __getattr__(self, name)
   1591             value = self._get_module(name)
   1592         elif name in self._class_to_module.keys():
-> 1593             module = self._get_module(self._class_to_module[name])
   1594             value = getattr(module, name)
   1595         else:

/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py in _get_module(self, module_name)
   1603             return importlib.import_module("." + module_name, self.__name__)
   1604         except Exception as e:
-> 1605             raise RuntimeError(
   1606                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1607                 f" traceback):\n{e}"

RuntimeError: Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
module 'torch.library' has no attribute 'register_fake'

**Comment by koito19960406** [comment]
Fixed this issue by making `torch` and `torchvision` version more flexible in ca045b7fd13394e65a0cfd52f1e0c0cb12672afd and b55b95bba3a6da713e27815809990ed25e0f7ee8
