### ISSUE TITLE
zensvi installation

### ISSUE THREAD

**Issue by matqr** [koito19960406/ZenSVI#79]
The main `README` uses `pip`, an `CONTRIBUTING.md` refers to `poetry`. Is there a preferred one? Why are both listed?

I'm also experiencing issues running `poetry install` as required in `CONTRIBUTING.md`

# Poetry Installation Method
brew

# Operating Sytem
MacOS 15.0.1

# Poetry version
1.8.3

```
Installing torch (2.4.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.4.1)
```

**Comment by koito19960406** [comment]
Hi @matqr, thanks for raising the issue.

> The main README uses pip, an CONTRIBUTING.md refers to poetry. Is there a preferred one? Why are both listed?

`pip` is for end users to install the package as most of them use it to install packages, while `poetry` is better for project dependency management. I developed this package with `poetry` thus I also recommend the contributors do the same.

> I'm also experiencing issues running poetry install as required in CONTRIBUTING.md

Please try `pip install poetry` to install poetry. I was able to run `poetry install` under the same environment as yours after installing poetry with pip.

I'll update [CONTRIBUTING.md ](https://github.com/koito19960406/ZenSVI/blob/main/CONTRIBUTING.md)soon to clarify this.

**Comment by matqr** [comment]
Got it! Weirdly I am still facing issues with that version of torch. It fails to update from 2.3.0 to 2.4.1.

I will keep looking into it.

**Comment by koito19960406** [comment]
I also suggest that you create a clean virtual environment for this (without torch or other packages installed)

1. create a virtual env (e.g., conda)
2. install poetry with pip
3. run `poetry install`

**Comment by matqr** [comment]
Yeah, tested it like that with 2 python versions (3.11 and 3.12) and got the same issues. Will debug it further this week.

**Comment by koito19960406** [comment]
@matqr please close this issue if you were able to solve this
