### ISSUE TITLE
'organization_id' error message

### ISSUE THREAD

**Issue by etoileboots** [koito19960406/ZenSVI#83]
KeyError "['organization_id'] not in index" with the following code to download street view imagery: 

from zensvi.download import MLYDownloader

mly_api_key = "api key" # removed for sake of privacy 
downloader = MLYDownloader(mly_api_key=mly_api_key)

# with a place name that works on OpenStreetMap:
downloader.download_svi("/content/tbilisi_images", input_place_name="Tbilisi")

**Comment by koito19960406** [comment]
@etoileboots 
Hi, thanks for pointing this out. This was due to some cases where there was no `organization_id` column in the returned json file. I fixed this in 770979fda417c9cbe3d5ce66534e3cc34f9c3764 and the new patch version `v0.12.11` now works without an error.
